<?php

namespace app\backend\models;

use app\components\Helper;
use Yii;

/**
 * This is the model class for table "article_tags".
 *
 * @property integer $id
 * @property string $tag
 * @property integer $article_id
 * @property integer $entity_id
 */
class EntityTags extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'entity_tags';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tag', 'entity_id'], 'required'],
            [['entity_id'], 'integer'],
            [['tag'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tag' => 'Tag',
            'entity_id' => 'Entity ID',
        ];
    }
    public static function normalize(string $tag)
    {
        return Helper::removeOddSpace(trim(mb_strtolower($tag)));
    }
    public function beforeSave($insert)
    {
        $this->tag = self::normalize($this->tag);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
